name: Go
on: [push]
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.12']
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - run: |
        go get -v -t ./...
        go test -v ./...
